CREATE TABLE |nomtaula| (
  ID int(11) unsigned NOT NULL auto_increment,
  ECLASS tinyint(2) unsigned NOT NULL default '0',
  SKIN tinyint(2) unsigned NOT NULL default '0',
  CATEGORY1 int(2) unsigned NOT NULL default '0',
  CATEGORY2 int(2) unsigned NOT NULL default '0',
  STATUS tinyint(2) unsigned NOT NULL default '0',
  VISIBILITY tinyint(2) unsigned NOT NULL default '0',
  CREATION datetime NOT NULL default '0000-00-00 00:00:00',
  START_TIME datetime NOT NULL default '0000-00-00 00:00:00',
  END_TIME datetime NOT NULL default '0000-00-00 00:00:00',
  CALENDAR_START_TIME datetime NOT NULL default '0000-00-00 00:00:00',
  CALENDAR_END_TIME datetime NOT NULL default '0000-00-00 00:00:00',
  MODIFICAT datetime NOT NULL default '0000-00-00 00:00:00',
  USUARICREAR varchar(255) NOT NULL default '',
  USUARIMODI varchar(255) NOT NULL default '',
  TITOL varchar(250) default NULL,
  URL_TITOL varchar(250) default NULL,
  SUBTITOL varchar(250) default NULL,
  RESUM text,
  DESCRIPCIO text,
  DESCRIPCIO2 text,
  LINK1 varchar(250) default NULL,
  TEXTLINK1 varchar(255) NOT NULL default '',
  FINESTRA1 tinyint(2) unsigned NOT NULL default '0',
  LINK2 varchar(255) default NULL,
  TEXTLINK2 varchar(255) NOT NULL default '',
  FINESTRA2 tinyint(2) unsigned NOT NULL default '0',
  LINK3 varchar(255) NOT NULL default '',
  TEXTLINK3 varchar(255) NOT NULL default '',
  FINESTRA3 tinyint(2) unsigned NOT NULL default '0',
  IMATGE1 varchar(255) default NULL,
  PEU_IMATGE1 varchar(255) NOT NULL default '',
  IMATGE2 varchar(255) default NULL,
  PEU_IMATGE2 varchar(255) NOT NULL default '',
  IMATGE3 varchar(255) default NULL,
  PEU_IMATGE3 varchar(255) NOT NULL default '',
  ADJUNT1 varchar(255) default NULL,
  TEXT_ADJUNT1 varchar(255) NOT NULL default '',
  ADJUNT2 varchar(255) default NULL,
  TEXT_ADJUNT2 varchar(255) NOT NULL default '',
  ADJUNT3 varchar(255) default NULL,
  TEXT_ADJUNT3 varchar(255) NOT NULL default '',
  DATA varchar(250) default NULL,
  AUTOR text NOT NULL default '',
  ORDRE INT(11) DEFAULT '0' NULL,
  PRIMARY KEY  (ID),
  KEY IDX_ECLASS (ECLASS),
  KEY IDX_CATEGORY1 (CATEGORY1),
  KEY IDX_CATEGORY2 (CATEGORY2)
);
