apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pv-claim
  namespace: bibliopro
  labels:
    app: php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi