build:
	docker build -t registry.io.imim.cloud/bibliopro-data:1.1 .
	docker push registry.io.imim.cloud/bibliopro-data:1.1

run:
	docker run -ti --rm registry.io.imim.cloud/bibliopro-data:1.0 sh -c 'ls -la /data' 
