apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-addoms-claim
  namespace: bibliopro
  createNamespace: true
  labels:
    app: apache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi