<?php

require ('../../config_admin.inc');

db_query("
ALTER TABLE PLANTILLA_DESC
ADD OP1 VARCHAR( 100 ) NOT NULL DEFAULT '|OP1|',
ADD OP2 VARCHAR( 100 ) NOT NULL DEFAULT '|OP2|',
ADD OP3 VARCHAR( 100 ) NOT NULL DEFAULT '|OP3|',
ADD OP4 VARCHAR( 100 ) NOT NULL DEFAULT '|OP4|',
ADD OP5 VARCHAR( 100 ) NOT NULL DEFAULT '|OP5|';
");
db_query("
ALTER TABLE PLANTILLA ADD OP SMALLINT( 5 ) NOT NULL DEFAULT '0';
");
db_query("
ALTER TABLE ESTATICA
ADD OP1 VARCHAR( 1 ) NOT NULL,
ADD OP2 VARCHAR( 1 ) NOT NULL,
ADD OP3 VARCHAR( 1 ) NOT NULL,
ADD OP4 VARCHAR( 1 ) NOT NULL,
ADD OP5 VARCHAR( 1 ) NOT NULL;
")
?>
