<?php

/////////////////                                          //////////////////
///////////////// ADMIN INTERFACE //////////////////
/////////////////                                          //////////////////

////// Generals /////
$messages["home"]="Portada";
$messages["back"]="<< Torna";
$messages["continue"]="Continua";
$messages["plantillanotrobada"]="<h4>Avís:</h4> No s'ha trobat la plantilla";
$messages["errordbcards"] = "<h4>Avís:</h4> No s'ha pogut crear DBCards.<br>\n";
$messages["errordbcardsnew"] = "<h4>Avís:</h4> No s'ha pogut crear una nova fitxa.<br>\n";
$messages["errordbcardscodi"]="<h4>Avís:</h4> No s'ha rebut el codi dbcards.<br>\n";
$messages["errordbcardscodinotfound"]="<h4>Avís:</h4> No existeix el registre sol·licitat.<br>\n";
$messages["errordbcardsupdate"]="<h4>Avís:</h4> No s'ha pogut actualitzar el registre.<br /><br />";
$messages["errordeletenocheck"]="<span class='grana11'>L'operació no s'ha realitzat perquè no heu seleccionat cap element.</span>";
$messages["close"]="Tanca";
$messages["cancel"]="Cancel·la";
$messages["backnotsave"]="Torna enrere sense desar les modificacions";
$messages["send"]="Envia";
$messages["sending"]="Enviant";
$messages["update"]="Actualitza";
$messages["create"]="Crea";
$messages["modify"]="Modifica";
$messages["save"]="Desa";
$messages["search"]="Cerca";
$messages["edit"]="Edita";
$messages["delete"]="Elimina";
$messages["deleted"]="Eliminada";
$messages["view"]="Visualitza";
$messages["change"]="Canvia";
$messages["duplicate"]="Duplica";
$messages["size"]="Mida";
$messages["duplicated"]="Duplicat";
$messages["orderby"]="Ordenar per";
$messages["confirmdelete"]="Confirmació d'eliminació";
$messages["searchnotfound"]="No s'ha trobat cap coincidència";
$messages["searchresults"]="Resultats de la cerca";
$messages["yes"]="Sí";
$messages["no"]="No";
$messages["backtolist"]="Torna al llistat";
$messages["youarein"]="Sou a";
$messages["shorttext"]="Text curts";
$messages["largetext"]="Text llargs";
$messages["alts"]="Alts imatges";
$messages["alt"]="Alt imatge";
$messages["images"]="Imatges";
$messages["files"]="Adjunts";
$messages["image"]="Imatge";
$messages["file"]="Adjunt";
$messages["upload"]="Puja";
$messages["folder"]="Carpeta";
$messages["creationdate"]="Data creació";
$messages["next"]="Següent";
$messages["previous"]="Anterior";
$messages["description"]="Descripció";
$messages["title"]="Títol";
$messages["keywords"]="Paraules clau";
$messages["left"]="Esquerra";
$messages["right"]="Dreta";
$messages["up"]="Superior";
$messages["none"]="Cap";
$messages["loading"]="Carregant...";
$messages["wait"]="Espereu";
$messages["printversion"]="Versió per a imprimir";
$messages["viewmapweb"]="Visualitza mapa web";
$messages["page"]="Pàgina";
$messages["for"]="per";
$messages["generate"]="Publica";
$messages["waitgenerate"]="Pendent de publicar";
$messages["utils"]="Utilitats";
$messages["to"]="a";
$messages["generating"]="Publicant pàgines...";
$messages["generatepagesfolders"]="Publica pàgines per carpeta";
$messages["generateallpages"]="Publica totes les pàgines";
$messages["viewpagenotfound"]="La pàgina no ha estat publicada";
$messages["continuesamefolder"]="Continua a la mateixa carpeta";
$messages["gonewfolder"]="Vés a la nova carpeta";
$messages["name"]="Nom";
$messages["title"]="Títol";
$messages["creationdate"]="Data creació";
$messages["modifydate"]="Data modificació";
$messages["status"]="Estat";
$messages["order"]="Ordre";
$messages["createregistry"]="Crea registre";
$messages["list"]="Llista";
$messages["publish"]="Publicar";
$messages["notpublish"]="No publicar";
$messages["unpublish"]="Despublicar";
$messages["preview"]="Previsualització";
$messages["notcategoriesdefined"]="No hi ha categories definides";
$messages["redirect"]="Espereu un moment, redireccionant la pàgina...";
$messages["notwait"]="O premeu aquí si no voleu esperar";
$messages["date"]="Data";
$messages["link"]="Enllaços";
$messages["url"]="Adreça";
$messages["text"]="Text";
$messages["newwindow"]="Nova finestra";
$messages["start"]="Inici";
$messages["end"]="Fi";
$messages["activate"]="Activar?";
$messages["dateformat"]="dd/mm/aaaa";
$messages["previewlog"]="Informe";
$messages["date"]="Data";
$messages["type"]="Tipus";
$messages["link"]="vincle";
$messages["height"]="Altura";
$messages["width"]="Amplada";
$messages["flash"]="Flash";
$messages["text"]="Text";
$messages["createdata"]="Creada el";
$messages["modifydata"]="i modificada el";
$messages["logout"]="Surt";
$messages["new"]="Nou";
$messages["vertical"]="Vertical";
$messages["horizontal"]="Horitzontal";
$messages["style"]="Estil";
$messages["backgroundcolor"]="Color de fons";
$messages["linemenu"]="Filet del menú";
$messages["bordercolor"]="Color border";
$messages["bordersize"]="Mida border";
$messages["newentry"]="Nova entrada";
$messages["level"]="Nivell";
$messages["invalidcode"]="El codi de comprovació especificat no és correcte";
$messages["securitycode"]="Codi de seguretat";
$messages["code"]="Codi";
$messages["addcategory"]="Afegeix categoria";
$messages["form"]="Formulari";
$messages["saveto"]="Desa a";
$messages["root"]="Arrel";
$messages["value"]="Valor";
$messages["obligatory"]="Obligatori";
$messages["small"]="Petit";
$messages["medium"]="Normal";
$messages["large"]="Gran";
$messages["field"]="camp";
$messages["plugins"]="Mòduls";
$messages["uploadmanager"]="Gestió d'arxius";
$messages["exportdata"]="Exporta dades";
$messages["others"]="Altres";
$messages["databasebackup"]="Còpia de seguretat de la base de dades";
$messages["dobackup"]="Fer una còpia de seguretat";
$messages["restorebackup"]="Restaura una copia de seguretat anterior";
$messages["registryhistory"]="Històric d'accions";
$messages["registryhistoryviewall"]="Visualitza històric d'accions de tots els usuaris";
$messages["registryhistoryviewmy"]="Visualitza el meu històric";
$messages["all"]="Tots";
$messages["action"]="Acció";
$messages["lastaction"]="Última acció";
$messages["from"]="Des de";
$messages["todate"]="fins a";
$messages["levelup"]="Puja un nivell";
$messages["refresh"]="Actualitza";

$messages["language"]="Idioma";
$messages["options"]="Opcions";
$messages["optionsadvanced"]="Opcions avançades";

$messages["move"]="Mou";

$messages["import"]="Importar";

$messages["active"]="Actiu";
$messages["inactive"]="Inactiu";

$messages["go"]="Fer";
$messages["db_connect_error"]="No s'ha pogut conectar amb la base de dades";
$messages["separator"]="Separador";
$messages["class"]="Classe";
$messages["apartat"]="Apartat";

//// head and foot /////
$messages["foodproduct"]="és un producte de";
$messages["headcontent"]="Continguts";
$messages["headdir"]="Carpetes";
$messages["headusers"]="Usuaris";
$messages["headtemplate"]="Plantilles";
$messages["headmenu"]="Menús";
$messages["headform"]="Formularis";
$messages["headutils"]="Utilitats";
$messages["headlogout"]="Surt de la sessió";
$messages["headgoweb"]="Vés al web";
$messages["orderenter"]="Ordre d'entrada";
$messages["categories"]="Categories";
$messages["menu"]="Menú";
$messages["model"]="Model";


///// login //////
$messages['loginbutton'] = 'Entra';
$messages['loginmessage'] = 'Introduïu el vostre nom d\'usuari i la clau d\'accés.';
$messages['loginerror'] = 'L\'usuari i/o la clau introduïts no són correctes.';
$messages['loginuser'] = 'Usuari';
$messages['loginkey'] = 'Clau';
$messages['logintitle'] = 'Accés al Gestor de continguts del Web';
$messages['loginhoudini'] = 'Houdini és el gestor de continguts de la web de '.$GLOBALS['CONFIG_SITENAME'].'. Per a qualsevol dubte sobre el manteniment o incidències tècniques, contacteu amb l\'administrador.';
$messages["registrylogin"]='Accés usuari';
$messages["registryloginnotexist"]='Error accés: Login no existeix o password erroni';
$messages["registryloginerrorpassword"]="Error accés: Password erroni";
$messages["registryloginerrorstatus"]="Error accés: Usuari inactiu";
$messages["registryloginerrorexpired"]="Error accés: Usuari caducat";
$messages["registrylogout"]="Sortida usuari";


//users//
$messages["user"]="Usuari";
$messages["userstitle"]="Gestió d'usuaris";
$messages["userstitlenew"]="Nou usuari";
$messages["userstitleupdate"]="Actualitza usuari";
$messages["userslist"]="Llistat d'usuaris";

////// user missatges /////
$messages["errordbusers"] = "<h4>Avís:</h4> No s'ha pogut crear DBUsers.<br>\n";
$messages["erroruserscodi"]="<h4>Avís:</h4> No s'ha rebut el codi d'usuari.<br>\n";
$messages["errorusersaccio"]="<h4>Avís:</h4> No s'ha rebut el codi d'acció.<br>\n";
$messages["errorusersdelconfirm"]="<h4>Avís:</h4> Per poder eliminar un usuari, heu d'activar la confirmació.<br>\n";
$messages["errorusersdel"]="<h4>Avís:</h4> No s'ha pogut eliminar l'usuari.<br>\n";
$messages["errorusersnomusuaritamany"]="Nom d'usuari no vàlid.<br>Comproveu que almenys tingui 3 caràcters.<br>\n";
$messages["errorloginutilitzat"] = "Nom utilitzat per un altre usuari.<br>\n";
$messages["errorusersclausdif"]="Les claus escrites no coincideixen. Torneu a escriure-les.<br>\n";
$messages["errorusersgeneral"]="<h4>Avís:</h4> No s'ha pogut actualitzar l'usuari.<br /><br />";
$messages["errorusersclaustamany"]="La clau ha de tenir almenys 3 caràcters.<br>";
$messages["erroreliminaruser"]="No s'ha pogut eliminar l'usuari/s: ";
$messages["usereliminat"]="S'ha eliminat l'usuari/s: ";
$messages["usernoseleccionat"]="Heu de seleccionar un usuari per eliminar-lo.";
$messages["usercanviclau"]="Deixar buit si no es vol canviar";
///user noms dels camps del//
$messages["userformlogin"]="Usuari";
$messages["userformpassword"]="Clau";
$messages["userformpasswordrepeat"]="Repetir clau";
$messages["userformemail"]="Correu electrònic";
$messages["userformname"]="Nom";
$messages["userformsurname1"]="Cognom 1";
$messages["userformsurname2"]="Cognom 2";
$messages["userformtelephon"]="Telèfon";
$messages["userformlevel"]="Nivell";
$messages["userformstat"]="Estat";
$messages["userformstatics"]="Estàtics";
$messages["userformdinamics"]="Dinàmics";
$messages["userformmenu"]="Menú";
$messages["userformdata"]="Continguts";





//plantilles
$messages["template"]="Plantilla";
$messages["templatenew"]="Nova plantilla";
$messages["templateregister"]="Registrar plantilla";
$messages["templatetitle"]="Gestió plantilles";
$messages["templatedefine"]="Definició de variables plantilla";
$messages["templatecompleted"]="Registre complet";
$messages["templatelist"]="Llistat de plantilles";


$messages["errortemplatedelconfirm"]="<h4>Avís:</h4> Per poder eliminar una plantilla, heu d'activar la confirmació.<br>\n";
$messages["templatedelconfirmok"]="La plantilla ha estat eliminada.<br>\n";
$messages["templateregistred"]="La plantilla ha estat registrada.";
$messages["templatemodify"]="Modifica plantilla registrada";
$messages["templatenotfound"]="La plantilla no ha estat generada";
///plantilles noms dels camps del//
$messages["templateformname"]="Nom de la plantilla";
$messages["templateformdescription"]="Descripció";
$messages["templateformshortfields"]="Núm. camps curts";
$messages["templateformlargefields"]="Núm. camps llargs";
$messages["templateformiamges"]="Núm. imatges";
$messages["templateformfiles"]="Núm. arxius adjunts";
$messages["templateformdata"]="Continguts";
$messages["templateformforothers"]="Aquesta plantilla és aplicable també per a les subcarpetes?";

//missatges upload plantilles
$messages["uploadtemplatetitol"]="Puja plantilla al servidor";
$messages["uploadtemplateok"]="La plantilla ha estat pujada";
$messages["uploadtemplatenone"]="Cap plantilla seleccionada per pujar";
$messages["uploadtemplatetoobig"]="La plantilla és massa gran";
$messages["uploadtemplateerrorcopy"]="No es pot copia la plantilla al servidor";
$messages["uploadtemplateginvalidformat"]="La plantilla no és vàlida. Ha de ser html";



//missatges error camps formulari
$messages["formerrorname"]="Introduïu el nom";
$messages["formerrorfields0"]="Cap dels camps no pot tenir valor 0";
$messages["formerrorname"]="Introduïu el camp";
$messages["formalertdeleteimage"]="Esteu segurs d´eliminar l´arxiu o imatge ?";


///////accions al registre///
//registre plantilles
$messages["templateregistrycreate"]="Nova plantilla registrada";
$messages["templateregistryupdate"]="Plantilla actualitzada";
$messages["templateregistrydelete"]="Plantilla eliminada";
$messages["userregistrycreate"]="Usuari creat";
$messages["userregistryupdate"]="Usuari actualitzat";
$messages["userregistrydelete"]="Usuari eliminat";


//static pages /////////////////7
$messages["staticpagestitle"]="Gestió de continguts estàtics";
$messages["staticpageslist"]="Pàgines";
$messages["staticpagesnamepage"]="Nom de la pàgina";
$messages["staticpagessearchoption"]="Apareix al cercador";
$messages["staticpagesselectoptions"]="Selecció de menús";
$messages["staticpagesselectoptionsbanner"]="Selecció de composicions de caixetes";
$messages["staticpagesimages"]="Imatges associades";
$messages["staticpagesfiles"]="Arxius adjunts";
$messages["staticpagescreate"]=$messages["createdata"];
$messages["staticpagemodify"]=$messages["modifydata"];
$messages["staticpagepreview"]="Previsualització de la pàgina";

$messages["staticpagepreviewselect"]="Selecció d'idioma";
$messages["staticpagepreviewselectlong"]="Seleccioneu els idiomes on s'aplica l'acció";
$messages["staticpagepreviewapply"]="Acció";
$messages["staticpagepreviewapplylong"]="Seleccioneu quina acció voleu realitzar";
$messages["staticpagepreviewaction"]="Confirmació";
$messages["staticpagepreviewactionlong"]="Cliqueu per confirmar";



$messages["staticpageerrorcreate"]="No es pot crear la pàgina. No existeix la plantilla";
$messages["staticpageerrorpreview"]="No es pot visualitzar la pàgina. No existeix la plantilla";
$messages["staticpageerrorcreateprintversion"]="No es pot crear la pàgina Versió per a imprimir. No existeix la plantilla";
$messages["staticpageerrorexist"]="La pàgina que voleu crear ja existeix en aquesta carpeta.<br>Trieu un altre nom per a la pàgina que  voleu crear.";
$messages["staticpageerrornotemplate"]="Cal que seleccioneu una plantilla que doni format a la pàgina que voleu crear.";
$messages["staticpageerrornoname"]="Cal que poseu un nom a la pàgina que voleu crear.";
$messages["staticpageerrornotfound"]="El registre sol·licitat no existeix.";
$messages["staticpageerrornoopen"]="Impossible obrir la plantilla.";
$messages["staticpagescreateok"]="Pàgina creada";
$messages["staticpagescreateprintversionok"]="Pàgina Versió per a imprimir creada";
$messages["staticpagesoptionsview"]="Visualitza la pàgina creada";
$messages["staticpagesoptionscreate"]="Crea pàgina";
$messages["staticpagessaveas"]="Desa pàgina com";
$messages["staticpagespreviewtemplate"]="Previsualització de la plantilla";
$messages["staticpageszoomtemplate"]="Visualitza plantilla ampliada";
$messages["staticpagesselecttemplate"]="Escolliu plantilla";
$messages["staticpagesdopreviewerror"]="Si us plau, seleccioneu una plantilla per a previsualitzar";
$messages["staticpagestemplatechanged"]="La pàgina ha estat canviada de plantilla";
$messages["staticpagesduplicatedexist"]="Ja existeix una pàgina duplicada amb el nom de còpia de...";

$messages["staticpagesareacontrolduplicate"]="Duplicar planes";
$messages["staticpagesduplicatemessage"]="Recordeu que quan dupliqueu una plana heu de renombrar <strong>totes les versions</strong> dels diversos idiomes. ";
$messages["staticpagesduplicateerrormessage1"] ="La plana ";
$messages["staticpagesduplicateerrormessage2"] = "ha estat renombrada com a";
$messages["staticpagesduplicateexplainmessage1"] = "Això és degut al fet que ja havíeu duplicat anteriorment la plana ";
$messages["staticpagesduplicateexplainmessage2"] = " i no havíeu renombrat totes les versions en els diversos idiomes. 	<br /><br />	Ara, aquestes versions han estat renombrades amb el nom que havíeu usat en la darrera duplicació: ";

$messages["staticpagesareacontrolduplicatelang"]="Importar contingut de l'idioma principal";
$messages["staticpagesduplicatelangmessage"]="Recordeu que quan importeu un idioma es sobrescriuran totes les parts que heu seleccionat, sense posibilitat de recuperació.";
$messages["staticpagesduplicatelanggeneral"]="Importar dades generals (nom, descripció i plantilla)";
$messages["staticpagesduplicatelangmenu"]="Importar menús";
$messages["staticpagesduplicatelangbanner"]="Importar caixetes";
$messages["staticpagesduplicatelangtext"]="Importar textos";
$messages["staticpagesduplicatelangimages"]="Importar imatges";
$messages["staticpagesduplicatelangadjunts"]="Importar adjunts";




$messages["staticpagesdeletefilesmessage1"]="ha estat eliminat";
$messages["staticpagesdeletefilesmessage2"]="no existeix al servidor. El camp ha estat esborrat.";
$messages["staticpagesmovepage"]="Canvia pàgina de carpeta";
$messages["staticpagescarpetnow"]="Carpeta actual";
$messages["staticpagesmovepagemessage"]="Escolliu la carpeta cap on voleu moure la pàgina";
$messages["errorstaticpagesdelconfirm"]="<h4>Avís:</h4> Per poder eliminar una pàgina, heu d'activar la confirmació.<br>\n";
$messages["staticpagesdelok"]="La pàgina han estat eliminada.";
$messages["staticpagesdelokonlydb"]="El registre ha estat esborrat de la base de dades. La pàgina no havia estat publicada.";
$messages["staticpagesinfochangetemplate"]="És possible que si feu un canvi de plantilla, alguns camps de text no siguin visibles.<br>Això no significa que els hàgiu perdut, sinó que la nova plantilla té menys camps per mostrar els continguts de la plana a que voleu assignar-la.";
$messages["staticpagesinfochangetemplatefromfolder"]="Heu mogut la pàgina a una carpeta on no es pot utilitzar la plantilla que ara té assignada.<br>Si us plau, escolliu una nova plantilla per a la pàgina";
$messages["staticpagesinfochangefolderok"]="La pàgina ha estat canviada de carpeta";
$messages["staticpagesinfochangefoldererror"]="La pàgina no s'ha pogut moure. Ja existeix una pàgina amb el mateix nom en aquesta carpeta.";
$messages["staticpagesareacontrolgenerate"]="Publica pàgines";
$messages["staticpagesareacontrolungenerate"]="Despublica pàgines";
$messages["staticpagesareacontrolungeneratepage"]="Pàgina despublicada";
$messages["staticpagesareacontrolnothing"]="No hi ha hagut canvis";
$messages["staticpagesareacontrolback"]="Torna a l'àrea de control";


///////accions static pages///
//registre
$messages["staticpagesregistryupdate"]="Pàgina actualitzada";
$messages["staticpagesregistrygenerate"]="Pàgina publicada";
$messages["staticpagesregistrytemplatechanged"]="Plantilla canviada";
$messages["staticpagesregistryduplicatedok"]="Pàgina duplicada";
$messages["staticpagesregistrydelete"]="Pàgina eliminada";
$messages["staticpagesregistryfolder"]="Pàgina canviada de carpeta";

//uploads
$messages['uploadvalidformat'] = "Formats vàlids";
$messages['uploadmaxsize'] = "Pes màxim";
$messages['uploadimageslognone']="Cap imatge seleccionada per pujar";
$messages['uploadimageslogtoobig']="La imatge és massa gran";
$messages['uploadimageslogerrorcopy']="No es pot copiar la imatge al servidor";
$messages['uploadimageslogok']="La imatge ha estat pujada al servidor";
$messages['uploadimagesloginvalidformat']="La imatge no és vàlida";
$messages['uploadfileslognone']="Cap arxiu seleccionat per pujar";
$messages['uploadfileslogtoobig']="L'arxiu és massa gran";
$messages['uploadfileslogerrorcopy']="No es pot copiar l'arxiu al servidor";
$messages['uploadfileslogok']="L'arxiu ha estat pujat al servidor";
$messages['uploadfilesloginvalidformat']="L'arxiu no és vàlid";




//dinamic contents //////////////////
$messages["dinamicstitle"]="Gestió de continguts dinàmics";
$messages["dinamicsviewinweb"]="Visualitza la carpeta al web";
$messages["dinamicsregistrycreate"]="Registre creat a la carpeta";
$messages["dinamicsregistrymodify"]="Registre modificat a la carpeta";
$messages["dinamicsxmlerrorcreate"]="No existeix el directori especificat. No s'ha pogut copiar l'arxiu xml";
$messages["dinamicsregistrypublish"]="Registre publicat a la carpeta";
$messages["dinamicsregistrynotpublish"]="Registre no publicat a la carpeta";
$messages["dinamicsregistryduplicate"]="Registre duplicat";
$messages["dinamicsregistrydelete"]="El registre ha estat esborrat";
$messages["dinamicsselectcategory"]="Escolliu categoria";
$messages["dinamicsformtitle"]="Títol";
$messages["dinamicsformsubtitle"]="Subtítol";
$messages["dinamicsformresum"]="Resum";
$messages["dinamicsformtext"]="Text extens";
$messages["treecategories"]="Arbre";
$messages["author"]="Autor";
$messages["dinamicsformselectdata"]="Tria una data";

/////  dinamic category //////////////
$messages['dincategoryedit'] = "Editar categories";
$messages['dincategorynewcat'] = "Nova categoria";
$messages['dincategoryeditcat'] = "Edita categoria";
$messages['dincategorytitle'] = "Gestió categories";
$messages['dinsubcategoryedit'] = "Editar subcategories";
$messages['dinsubcategorynewcat'] = "Nova subcategoria";
$messages["dinsubcategoryentrydelete"]="Categoria eliminada";
$messages["dinsubcategoryerrordelete"]="El registre no ha pogut ser borrat de la base de dades.";




////// configtext /////
$messages['configtexttitle']="Gestió de continguts estàtics";
$messages['configtext_guardar'] = 'Desa';
$messages['configtextok'] = 'Textos desats correctament';
$messages['configtext_correcte'] = 'Textos desats correctament';
$messages['configtexterror'] = 'No s\'han pogut guardar els textos, torneu-ho a intentar';

//////  banners  ////////
$messages['bannersgrouppreview']="Previsualització de composició";
$messages['bannerspreview']="Previsualització de caixeta";
$messages['bannersgrouptitle']="Gestió de composicions";
$messages['bannerstitle']="Gestió de caixetes";
$messages['bannersgroup']="Composicions";
$messages['banners']="Caixetes";
$messages['banner']="Caixeta";
$messages['bannersgroupcreate']="Crea composició";
$messages['bannerscreate']="Crea caixetes";
$messages['bannersgroupmodif']="Modifica composició";
$messages['bannersmodif']="Modifica caixeta";
$messages['bannersgroupviewerror']="La composició no ha estat generada";
$messages['bannersviewerror']="La caixeta no ha estat generada";
$messages['bannersgrouperror1']="La composició que voleu crear ja existeix amb aquest nom.<br>Trieu un altre nom per la composició que  voleu crear.";
$messages['bannersgrouperror2']="Cal que poseu un nom a la composició que voleu crear.";
$messages['bannerserror1']="La caixeta  que voleu crear ja existeix amb aquest nom.<br>Trieu un altre nom per la caixeta que voleu crear.";
$messages['bannerserror2']="Cal que poseu un nom a la caixeta que voleu crear.";
$messages["bannerscreatedata"]=$messages["createdata"];
$messages["bannersmodifydata"]=$messages["modifydata"];
$messages["bannersnum"]="Nombre de caixetes";
$messages["bannererrorconfirm"]="<h4>Avís:</h4> Per poder eliminar un element, heu d'activar la confirmació.<br>\n";
$messages["bannererrordbcard"]=$messages["errordbcards"];
$messages['bannerlogdelete'] = 'El registre i la caixeta han estat eliminats.';
$messages['bannerlogdelete2'] = 'El registre ha estat esborrat de la base de dades. La caixeta no havia estat generada.';
$messages['bannergrouplogdelete'] = 'El registre i la composició han estat eliminats.';
$messages['bannergrouplogdelete2'] = 'El registre ha estat esborrat de la base de dades. La composició no havia estat generada.';
$messages['bannersselect'] = "Selecciona tipus de caixeta per crear";
$messages['bannersgroupselect'] = "Selecciona caixetes";
$messages['bannersselectpreview'] = 'Previsualització del tipus de caixeta';
$messages['bannersgroupselect'] = 'Selecciona les caixetes';
$messages['bannersselecok'] = 'Les composicions de caixetes han estat actualitzades correctament';
$messages['bannersselectitle'] = 'Selecció de composicions de caixetes';
$messages['bannersselectitleutils']="Selecciona combinacions de caixetes";
$messages["errorsbannersdelconfirm"]="<h4>Avís:</h4> Per poder eliminar una caixeta ha d'activar la confirmació.<br>\n";
$messages["errorsbannersgroupdelconfirm"]="<h4>Avís:</h4> Per poder eliminar una composició ha d'activar la confirmació.<br>\n";

//carpetes
$messages["folderstitle"]="Gestió de carpetes";
$messages["foldersstatictitle"] = "Carpeta estàtica";
$messages["foldersregistrycreated"] = "Carpeta creada";
$messages["foldersregistrydelete"] = "Carpeta eliminada";
$messages["foldersregistryupdate"] = "Carpeta actualitzada";
$messages["foldersformerrorname"]="Introduïu un nom per la carpeta que voleu crear.";
$messages["folderserrornorepeat"]="La carpeta ja existeix o el nom no és vàlid, no es poden crear 2 carpetes amb el mateix nom.";
$messages["folderserrornovalid"]="La carpeta no te un nom vàlid, canviï el nom de la carpeta.";
$messages["folderserrorcreate"]="S'ha produït un error en la creació de la carpeta";
$messages["folderserrorupdate"]="S'ha produït un error en l'actualitzar carpeta";
$messages["folderserrordelete"]="S'ha produït algun error en l'eliminació de la carpeta";
$messages["folderconfirmdelete"]="Esteu segurs d'eliminar la carpeta?<br>S'eliminarà la carpeta, les subcarpetes i les pàgines.";
$messages["folderconfirmdeleteinfo"]="Llista de carpetes que s'eliminaran";
$messages["foldersdinamictitle"] = "Carpeta dinàmica";
$messages["foldersregistrydinamiccreated"] = "Carpeta dinàmica creada";
$messages["foldersregistrydinamicupdate"] = "Carpeta dinàmica actualitzada";
$messages["folderserrorcreatedb"]="S'ha produït un error en inserir la nova carpeta dinàmica a la bbdd";
$messages["folderserrordeletedb"]="S'ha produït un error en eliminar la taula";
$messages["folderserrortoolarge"]="El nom de la carpeta és massa llarg";
$messages["folderserrortemplates"]="Error: Alguna de les plantilles no existeix!";
$messages["folderserrornotexist"]="Error: La carpeta no existeix!";
$messages["folderserrortemplate"]="La plantilla seleccionada no existeix";
$messages["folderconfirmdinamicdelete"]="Esteu segurs d'eliminar la carpeta?<br>S'eliminarà la carpeta, la seva taula i totes les seves dades.";
$messages["foldersdinamicformtitlesection"]="Títol de la secció";
$messages["foldersdinamicformsubtitlesection"]="Subtítol de la secció";
$messages["foldersdinamicformparagraphsection"]="Apartat de la secció";
$messages["foldersdinamicformintro"]="Introducció";
$messages["foldersdinamicformrss"]="Entrades a l'rss";
$messages["folderconfirmdeleteconfirm"]="Reescriu el codi de la imatge al camp codi per fer efectiva l'operació. El sistema no distingeix entre majúscules i minúscules.";
$messages["folderisinitial"] = "Voleu que la molla de pa començi en aquesta carpeta?";

////// view rss //////
$messages['viewrsstitle']="Gestió de visualitzadors de rss";
$messages['viewrsscreate']="Crea visualitzador";
$messages['viewrss']="Visualitzadors";
$messages["viewrsserrorconfirm"]="<h4>Avís:</h4> Per poder eliminar un element, heu d'activar la confirmació.<br>\n";
$messages['viewrsslogdelete'] = 'El registre i el visualitzador han estat eliminats.';
$messages['viewrsslogdelete2'] = 'El registre ha estat esborrat de la base de dades. El visualitzador no havia estat generat.';
$messages['viewrssmodif']="Modifica visualització";
$messages['viewrsslink']="Adreça fitxer rss";
$messages['viewrssmax']="Màxim d'entrades per mostrar";
$messages['viewrsstemplate']="Plantilla";
$messages['viewrssviewerror']="El visualitzador no ha estat generat";
$messages['viewrsspreview'] = "Previsualització del visualitzador";
$messages["errorsviewrssdelconfirm"]="<h4>Avís:</h4> Per poder eliminar un visualitzador rss ha d'activar la confirmació.<br>\n";

// menus ///
$messages["menutitle"]="Gestió de menús";
$messages["menuregistrygenerate"]="Menú publicat";
$messages["menuregistrycreate"]="Menú creat";
$messages["menuregistrydelete"]="Menú eliminat";
$messages["menuregistryupdate"]="Menú actualitzat";
$messages["menuregistryduplicated"]="Menú duplicat";
$messages["menuregistryentrydelete"]="Entrada menú eliminada";
$messages["menunotfound"]="El menú no ha estat publicat";
$messages["menuerrorformname"]="Introduïu un nom al menú que voleu crear.";
$messages["menuerrorformdescription"]="Introduïu una descripció al menú que voleu crear.";
$messages["menujavascript"]="Menú desplegable";
$messages["menuaccessible"]="Menú desplegable i accessible";
$messages["menunewitem"]="Crea entrada del menú";
$messages["menulistitems"]="Llista entrades del menú";
$messages["menuerrorcreate"]="El menú  que voleu crear ja existeix amb aquest nom.<br>Trieu-ne un altre de diferent.";
$messages["menuerrorduplicate"]="Ja existeix un menú duplicat amb el nom de còpia de...<br><font class=\"text10\"><b>Desa menú com:</b></font><br>";
$messages["menuformatwindow"]="Format nova finestra";
$messages["submenunewitem"]="Crea entrada submenú";
$messages["menuerrordelete"]="El registre no ha pogut ser esborrat de la base de dades.";
$messages["menuformforothers"]="Aquest menú és aplicable també per a les subcarpetes?";

//formularis
$messages["formstitle"]="Gestió de formularis";
$messages["formscreate"]="Crear formulari";
$messages["formsconfig"]="Configurar formulari";
$messages["formsconfigemailreceipt"]="Correu electrònic del receptor";
$messages["formsconfigurlreturn"]="Vincle de resposta";
$messages["formserrorcreate"]="El formulari que voleu crear ja existeix amb aquest nom.<br>Trieu un altre nom per al formulari que  voleu crear.";
$messages["formerrorduplicate"]="Ja existeix un formulari duplicat amb el nom de còpia de...<br><font class=\"text10\"><b>Desa formulari com:</b></font><br>";
$messages["formcreatefield"]="Crea camp formulari";
$messages["formlistfield"]="Llista camps del formulari";
$messages["formselectfield"]="Seleccioneu tipus de camp";
$messages["formtext"]="Quadre de<br>text d'una<br>línia";
$messages["formhidden"]="Camp ocult";
$messages["formtextarea"]="Quadre de<br>text amb<br>desplaçament";
$messages["formcombobox"]="Menú<br>desplegable";
$messages["formcheckbox"]="Casella de<br>verificació";
$messages["formradiobutton"]="Botó d'opció";
$messages["formupload"]="Adjuntar fitxer";
$messages["formtextdescription"]="Text de<br>descripció";
$messages["formregistryfielddeleted"]="Entrada menú eliminada";
$messages["formerrorcreate"]="No és pot crear el formulari. No existeix la plantilla";
$messages["formerrorpreview"]="No és pot visualitzar el formulari. No existeix la plantilla";


//messages formularis
$messages["forminfo"]="Si creeu un menú desplegable, les diverses opcions d'aquest han d'anar separades per una coma en el camp Valor. (Ex: si,no,ns/nc)<br><br>El camp Mida només s'utilitza en els camps de tipus Quadre de text d'una línia i Quadre de text amb desplaçament.";
$messages["formsmessages1"]="Introduïu un títol al formulari que voleu crear.";
$messages["formsmessages2"]="Introduïu un nom al formulari que voleu crear.";
$messages["formsmessages3"]="Introduïu el correu electrònic que rebrà el formulari.";
$messages["formsmessages4"]="Introduïu l'adreça a la qual es redireccionarà l´usuari que envia el formulari.";
$messages["formsmessagesgeneric"]="Introduïu el";


$messages["imagemanager"]="Gestor d'imatges";

//metatags
$messages["definedmetas"]="Metas definits";
$messages["utilsmetas"]="Gestió de metatags";
$messages["filesmetas"]="Fitxers de metatags";
$messages["previewmetas"]="Previsualització de metatags";
$messages["deletemetas"]="Confirmació d'eliminació del metatag seleccionat";
$messages["addmetasfile"]="Afegeix fitxer de metatags";
$messages["actionuploadmetas"]="Puja fitxer metatags";
$messages["actiondeletemetas"]="Fitxer metatags eliminat";
$messages["alertnofilemetas"]="Incorrecte: no hi ha cap fitxer seleccionat.";
$messages["alertfilesizemetas"]="Incorrecte: la mida del fitxer supera 1 Mb.";
$messages["alertfileexistmetas"]="Incorrecte: el fitxer de metatags ja existeix.";
$messages["alerterrormetas"]="Incorrecte: No s'ha pogut crear el fitxer de metatags.";
$messages["alterdeletemetas"]="Incorrecte:per poder esborrar, s'ha d'activar la confirmació";
$messages["alertdirmetas"]="El directori metatags no existeix";


//estadístiques web
$messages["statistics"]="Estadístiques del web";
$messages["timestatistics"]="Estadístiques temporals";
$messages["globalstatistics"]="Estadístiques globals";
$messages["detailedstatistics"]="Estadístiques detallades";

//enquesta
$messages['polltitle']="Gestió d'enquestes";
$messages['listpoll']="Enquesta";
$messages['pollcreate']="Crear Enquesta";
$messages['poll']="Enquestes";
$messages['pollmodif']="Modificar enquesta";
$messages['polltemplate']="Plantilla";
$messages['pollviewerror']="L'enquesta no ha estat generada";
$messages['pollquerytitle']="Gestió de respostes";
$messages['pollquerycreate']="Crear resposta";
$messages['pollquery']="Respostes";
$messages['pollquerymodif']="Modificar resposta";
$messages['pollerror1']="L'enquesta que voleu crear ja existeix amb aquest nom.<br>Trieu-ne un altre de diferent.";
$messages['pollerror2']="Cal que poseu un nom a l'enquesta que voleu crear.";
$messages['polllogdelete'] = 'El registre i l\'enquesta han estat eliminades.';
$messages['polllogdelete2'] = 'El registre ha estat borrat de la base de dades. L\'enquesta no havia estat generada.';
$messages["errorspolldelconfirm"]="<h4>Avís:</h4> Per poder eliminar una enquesta ha d'activar la confirmació.<br>\n";
$messages["errorspollquerydelconfirm"]="<h4>Avís:</h4> Per poder eliminar una resposta ha d'activar la confirmació.<br>\n";
$messages['pollquerylogdelete'] = 'La resposta han estat eliminada.';

// grups uploads

$messages['uploadgrouptitle'] = "Gestió de grups d'uploads";
$messages['uploadgroupgroup'] = "Grup";
$messages['uploadgrouptitlenew'] = "Nou";
$messages['uploadgroupregistrycreate'] = "Usuari afegit al grup upload";
$messages['uploadgroupperms'] = "Permisos";

//devel_file_browser
$messages['devel_file_browser'] = 'Gestor de fitxers';
$messages['devel_file_browser_select'] = 'Selecciona la zona on vols accedir';


// calendari
$messages["calendar"] = "Calendari";

//newsletters
$messages['newsletterstitle']="Gestió de Butlletins digitals";
	$messages["website"] = "Gestió de butlletins digitals";
	$messages["portada"] = "Portada";
	$messages["soua"] = "Sou a";
	$messages["opcions"] = "Opcions";
	$messages["editoranoticies"] = "Editora de notícies";
	$messages["editoracategories"] = "Editora de categories";
	$messages["editoranewsletters"] = "Editora de butlletins";
	$messages["noticiesnewsletter"] = "Notícies butlletins";
	$messages["crearnoticia"] = "Crear notícia";
	$messages["llistatiopcions"] = "Llistat i opcions";
	$messages["cercar"] = "Cercar";
	$messages["veurenoticia"] = "Veure notícia";
	$messages["editarnoticia"] = "Editar notícia";
	$messages["eliminarnoticia"] = "Eliminar notícia";
	$messages["llegendes"] = "Llegendes";
	$messages["titol"] = "Títol butlletí";
	$messages["titol_descrip"] = "Títol descripció";
	$messages["descripcio"] = "Descripció";
	$messages["model"] = "Model";
	$messages["creacio"] = "Creació";
	$messages["estat"] = "Estat";
	$messages["confirmacioeliminacio"] = "Confirmació d'eliminació";
	$messages["eliminar"] = "Eliminar";
	$messages["titolobligatori"] = "El camp 'Títol' és obligatori!";
	$messages["numobligatori"] = "El camp 'Número' és obligatori!";
	$messages["carregant"] = "Carregant...";
	$messages["subtitol"] = "Subtítol";
	$messages["lloc"] = "Lloc";
	$messages["datalloc"] = "Data";
	$messages["resum"] = "Resum";
	$messages["descripcio"] = "Descripció";
	$messages["nom"] = "Nom";
	$messages["carrec"] = "Càrrec";
	$messages["imatges"] = "Imatge";
	$messages["imatge"] = "Imatge";
	$messages["formats"] = "Formats";
	$messages["midamaxima"] = "Mida màxima";
	$messages["adjunts"] = "Arxius adjunts";
	$messages["adjunt"] = "Arxiu";
	$messages["nomarxiu"] = "Nom arxiu";
	$messages["aneualweb"] = "Aneu al web";
	$messages["aneualdoc"] = "Aneu al document";
	$messages["mesinfo"] = "informaci&oacute;";
	$messages["linksnoticiesnewsletter"] = "Enllaços notícies butlletí";
	$messages["tornar"] = "Tornar";
	$messages["capimgsel"] = "No s'ha seleccionat l'imatge";
	$messages["caparxsel"] = "No s'ha seleccionat l'arxiu";
	$messages["imgmassagran"] = "Massa gran l'imatge";
	$messages["arxmassagran"] = "Massa gran l'arxiu";
	$messages["noespotcopiarimg"] = "No es pot copiar l'imatge";
	$messages["noespotcopiararx"] = "No es pot copiar l'arxiu";
	$messages["shapujatimg"] = "S'ha pujat l'imatge";
	$messages["shapujatarx"] = "S'ha pujat l'arxiu";
	$messages["imgnovalida"] = "No es vàlida l'imatge";
	$messages["arxnovalid"] = "No es vàlid l'arxiu";
	$messages["capdocsel"] = "No s'ha seleccionat cap document";
	$messages["docmassagran"] = "El document és massa gran";
	$messages["noespotcopiardoc"] = "No es pot copia el document";
	$messages["shapujatdoc"] = "S'ha pujat el document";
	$messages["docnovalid"] = "El document no és vàlid";
	$messages["previsualitzacio"] = "Previsualització";
	$messages["confirmar"] = "Confirmar";
	$messages["modificar"] = "Modificar";
	$messages["informe"] = "Informe";
	$messages["aplicarcanvis"] = "Aplicar canvis";
	$messages["eliminatda"] = "eliminat/da";
	$messages["jahasiguteliminatda"] = "ja ha sigut eliminat/da";
	$messages["esperiredirec"] = "Esperi un moment, redireccionant la pàgina...";
	$messages["premisinovolesperar"] = "O premi aquí si no vol esperar";
	$messages["enllac"] = "Enllaç";
	$messages["veuredoc"] = "Veure document";
	$messages["veurearx"] = "Veure arxiu";
	$messages["enllacosrelacionats"] = "Enllaços relacionats";
	$messages["activarconfirmacio"] = "Incorrecte: Per a poder borrar s'ha d'activar la confirmació";
	$messages["noticiaeliminada"] = "La notícia ha sigut eliminada";
	$messages["continuar"] = "Continuar";
	$messages["error1"] = "Error: No s'ha rebut el codi de confirmació";
	$messages["error2"] = "Error: No s'ha pogut crear dbCards";
	$messages["error3"] = "Error: No s'ha trobat la plantilla";
	$messages["error4"] = "Error: No s'ha pogut crear una nova fitxa";
	$messages["error5"] = "Error: No s'ha pogut actualitzar el registre";
	$messages["resulcerca"] = "Resultats de la cerca";
	$messages["noresul"] = "No s'ha trobat cap coincidència!";
	$messages["categoriesnoticies"] = "Categories notícies";
	$messages["crearcategoria"] = "Crear categoria";
	$messages["editarcategoria"] = "Editar categoria";
	$messages["eliminarcategoria"] = "Eliminar categoria";
	$messages["color"] = "Color";
	$messages["ordre"] = "Ordre";
	$messages["pujar"] = "Pujar";
	$messages["baixar"] = "Baixar";
	$messages["categoriaeliminada"] = "La categoria ha sigut eliminada";
	$messages["canviarordre"] = "Canviar l'ordre de les categories";
	$messages["selecnoticies"] = "Selecció de notícies";
	$messages["elegircategoria"] = "Elegir categoria";
	$messages["seleccionar"] = "Seleccionar";
	$messages["cercarnoticies"] = "Cercar notícies";
	$messages["perparaulaclau"] = "Per paraula clau";
	$messages["perdata"] = "Per data";
	$messages["llistar"] = "Llistar";
	$messages["elegirnoticia"] = "Elegir notícia";
	$messages["newsletters"] = "Gestió de Butlletins digitals";
	$messages["crearnewsletters"] = "Crear butlletí";
	$messages["veurenewsletter"] = "Veure butlletí";
	$messages["editarnewsletter"] = "Editar butlletí";
	$messages["eliminarnewsletter"] = "Eliminar butlletí";
	$messages["enllestit"] = "Enllestit";
	$messages["newslettereliminat"] = "El butlletí ha sigut eliminat";
	$messages["visualitzarmodel"] = "Visualitzar model escollit";
	$messages["afegirnoticia"] = "notícia";
	$messages["afegirnoticia2"] = "contingut";
	$messages["files"] = "Files";
	$messages["columnes"] = "Columnes";
	$messages["mostrarnoticiesamb"] = "Mostrar notícies amb";
	$messages["separacionoticies"] = "Aspecte de les línies separadores de notícies";
	$messages["continues"] = "Continues";
	$messages["discontinues"] = "Discontinues";
	$messages["numero"] = "Número";
	$messages["noticiabutlleti"] = "Notícia butlletí";
	$messages["noticiacomplerta"] = "Notícia complerta";
	$messages["infolegal"] = "Info legal";
	$messages["tancar"] = "Tancar";
	$messages["peu"] = "&copy; ".date('Y')." Mercabarna";
	$messages["titolnewsletterspublics"] = "Butlletí de Mercabarna, el mercat central de Barcelona.";
	$messages["titolnewsletterpublic"] = "Butlletí de Mercabarna, el mercat central de Barcelona.";
	$messages["index"] = "Índex";
	$messages["pagina"] = "Pàgina";
	$messages["contacte"] = "Contacte";
	$messages["edicionsanteriors"] = "Edicions anteriors";
	$messages["imprimir"] = "Imprimir";
	$messages["alta"] = "Subscriure's";
	$messages["baixa"] = "Donar-se de baixa";
	$messages["amic"] = "Enviar a un amic";
	$messages["mescontingut"] = "Not&iacute;cies anteriors";
	$messages["editorabanners"] = "Editora de banners";
	$messages["bannersnewsletter"] = "Banners butlletí";
	$messages["crearbanner"] = "Crear banner";
	$messages["veurebanner"] = "Veure banner";
	$messages["editarbanner"] = "Editar banner";
	$messages["eliminarbanner"] = "Eliminar banner";
	$messages["link"] = "Link";
	$messages["bannereliminat"] = "Banner eliminat";
	$messages["afegirbanner"] = "banner";
	$messages["selecbanners"] = "Selecció de banners";
	$messages["cercarbanners"] = "Cercar banners";
	$messages["elegirbanner"] = "Elegir banner";
	$messages["noexist"] = "No hi ha resultats, ja està tot introduit al Butlletí";
	$messages["modelobligatori"] = "No heu escollit cap model!";
	$messages["noticiesjaintroduides"] = "Notícies ja introduides en algun butlletí del mateix model.";
	$messages["controlchtml"] = "Després de marcar el codi, premeu 'Control + C' per copiar-lo.";
	$messages["marcarcodihtml"] = "Marcar codi HTML";
	$messages["imatge_descrip"] = "Imatge descripció";
	$messages["afegir_editar1"] = "Afegir/editar dades";
	$messages["afegir_editar2"] = "Afegir/editar";
	$messages["sumari"] = "SUMARI";
	$messages["foodproduct"] = "és un producte de";
	$messages["staff"] = "EQUIP DE TREBALL";


?>
