repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: mysql
    chart: bitnami/mysql
    namespace: mysql
    createNamespace: true
    values:
      - ./mysql-values.yaml