
<table class="peuadmin" cellpadding="0" cellspacing="0" summary="peu p&agrave;gina">
  <tr>
     <td class="top">
      <a href="#top"><img src="../../../../../public/media/comu/admin/pujar_houdini.gif" alt="" /></a>
    </td>
    <td class="credits">
      <a href="http://houdini.antaviana.net/" target="_blank"><img src="../../../../../public/media/comu/admin/peu_houdini.gif" alt="Houdini" /></a>
      &eacute;s un producte de
      <a href="http://www.antaviana.net" target="_blank"><img src="../../../../../public/media/comu/admin/peu_antaviana.gif" alt="Can Antaviana" /></a>
      &copy; 2003-<?php echo date('Y'); ?>
    </td>
  </tr>
</table>


</body>
</html>