apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: bibliopro
  labels:
    app: php
spec:
  ports:
    - port: 80
      protocol: TCP
      name: tcp-80
      targetPort: 80
  selector:
    app: php