apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: bibliopro
  labels:
    app: apache
    version: 1.0.7
spec:
  selector:
    matchLabels:
      app: bibliopro
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: apache-pvc
      labels:
        app: bibliopro
        version: "1.0.7"
    spec:
      initContainers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.5
        args:
        - "-ssh"
        - "-repo=git@git.imim.cat:antaviana/bibliopro.git"
        - "-dest=bibliopro"
        - "-branch=master"
        - "-depth=1"
        - "-timeout=500"
        - "-add-user"
        - "-root=/tmp/git"
        - "-one-time"
        volumeMounts:
        - name: apache-pvc
          mountPath: /tmp/git
          subPath: data4
        - name: git-secret
          mountPath: /etc/git-secret
          readOnly: true
        securityContext:
          runAsUser: 104 # git-sync user
      - name: init-folders
        image: ubuntu:18.04
        args:
        - "bash"
        - "-c"
        - |
          folders=( media/upload )
          for f in "${folders[@]}"
          do
            if [ ! -d /data/$f ]; 
            then 
                if [ -d /data/data4/bibliopro/src/$f ];
                then
                        cp -r /data/data4/bibliopro/src/$f /data 
                        rm -rf /data/data4/bibliopro/src/$f 
                else
                        mkdir -p /data/$f
                fi
                chown -R www-data:www-data /data/$f
            fi 
            if [ -d /data/data4/bibliopro/src ];
            then
                ln -s /data/$f /data/data4/bibliopro/src/$f
            fi
          done
          if [ -d /data/data4/bibliopro/src ];
          then
            chown -R www-data:www-data /data/data4/bibliopro/src
          fi
        volumeMounts:
        - name: apache-pvc
          mountPath: /data
      securityContext:
        fsGroup: 65533 # to make SSH key readable
      terminationGracePeriodSeconds: 30
      containers:
      - image: registry.io.imim.cloud/bibliopro:1.2
        name: webserver
        env:
        - name: PASSWORD
          value: o6ejbbmGbeXhdSemSEhb
        - name: DATABASE
          value: biblioprodatabase
        - name: USERNAME
          value: biblioprouser
        - name: HOSTNAME
          value: mysql
        - name: HTTPS
          value: "true"
        volumeMounts:
        - name: apache-pvc
          mountPath: /var/www/html
          subPath: data4/bibliopro/src
        - name: apache-pvc
          mountPath: /data
         #securityContext:
         #runAsUser: 104 # git-sync user
      imagePullSecrets:
      - name: registryioimimcloud
      volumes:
      - name: apache-pvc
        persistentVolumeClaim:
          claimName: apache-addoms-claim
      - name: git-secret
        secret:
          secretName: git-secret
          defaultMode: 0400
