repositories:
  - name: bibliopro
    url: helm repo add bibliopro git+https://git.imim.cat/antaviana/bibliopro@bibliopro/bibliopro-chart?ref=main --debug

releases:
  - name: bibliopro
    chart: bibliopro/bibliopro
    namespace: bibliopro
    createNamespace: true
    values:
#      - ./bibliopro-values.yaml