repositories:
  - name: bibliopro
    url: git+https://git.imim.cat/antaviana/bibliopro@bibliopro/chart?ref=main

releases:
  - name: bibliopro
    chart: bibliopro/charts
    namespace: bibliopro
    createNamespace: true
    values:
#      - ./bibliopro-values.yaml