repositories:
  - name: bibliopro2
    url: git+https://github.com/jmcassany/bibliopro2@biblipro2-chart?ref=main
        
releases:
  - name: bibliopro2
    chart: bibliopro2/bibliopro2
    namespace: bibliopro
    createNamespace: true
