
<ul class="menu menu_vertical nav clearfix menu_normal">
<li class="<?php
          if("/cuestionarios/index.html"== $rutaplana or "/cuestionarios/index.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/cuestionarios/index.html">Patient Reported Outcomes y Calidad de Vida relacionada con la Salud</a>
<ul>
<li class="<?php
          if("/cuestionarios/definicion_y_clasificacion.html"== $rutaplana or "/cuestionarios/definicion_y_clasificacion.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/cuestionarios/definicion_y_clasificacion.html">Definición y Clasificación</a></li>
<li class="<?php
          if("/cuestionarios/desarrollo-adaptacion.html"== $rutaplana or "/cuestionarios/desarrollo-adaptacion.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/cuestionarios/desarrollo-adaptacion.html">Desarrollo y Adaptación</a></li>
<li class="<?php
          if("/cuestionarios/para-que-se-usan.html"== $rutaplana or "/cuestionarios/para-que-se-usan.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/cuestionarios/para-que-se-usan.html">Para qué se usan</a></li>

</ul>
</li>
<li class="<?php
          if("/cuestionarios/derechos-autores.html"== $rutaplana or "/cuestionarios/derechos-autores.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/cuestionarios/derechos-autores.html">Derechos de los autores</a></li>
<li class="<?php
          if("/cuestionarios/america-latina.html"== $rutaplana or "/cuestionarios/america-latina.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/cuestionarios/america-latina.html">América Latina</a></li>
<li class="<?php
          if("/cuestionarios/internacional.html"== $rutaplana or "/cuestionarios/internacional.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/cuestionarios/internacional.html">Internacional</a></li>
<li class="<?php
          if("/sobre_empro/index.html"== $rutaplana or "/sobre_empro/index.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/sobre_empro/index.html">Evaluación científica EMPRO (Evaluating Measures of Patient Reported Outcomes)</a></li>

</ul>
