
<ul class="menu menu_vertical information clearfix menu_normal">
<li class="authors<?php
          if("/informacion-autores/index.html" == $rutaplana or "/informacion-autores/index.html" == $_SERVER["REQUEST_URI"]) {
            ?> current<?php
            }
        ?>"><a href="/informacion-autores/index.html">Información para autores</a></li>
<li class="empro<?php
          if("/sobre_empro/index.html" == $rutaplana or "/sobre_empro/index.html" == $_SERVER["REQUEST_URI"]) {
            ?> current<?php
            }
        ?>"><a href="/sobre_empro/index.html">Evaluación científica EMPRO</a></li>
<li class="sponsor<?php
          if("/informacion-patrocinio/index.html" == $rutaplana or "/informacion-patrocinio/index.html" == $_SERVER["REQUEST_URI"]) {
            ?> current<?php
            }
        ?>"><a href="/informacion-patrocinio/index.html">Información para y sobre patrocinio</a></li>

</ul>
