
<ul class="menu menu_vertical nav clearfix menu_normal">
<li class="<?php
          if("/informacion-autores/index.html"== $rutaplana or "/informacion-autores/index.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-autores/index.html">Bienvenida</a></li>
<li class="<?php
          if("/informacion-autores/cuestionarios_adaptados.html"== $rutaplana or "/informacion-autores/cuestionarios_adaptados.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-autores/cuestionarios_adaptados.html">Propiedad intelectual</a>
<ul>
<li class="<?php
          if("/informacion-autores/cuestionarios_adaptados.html"== $rutaplana or "/informacion-autores/cuestionarios_adaptados.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-autores/cuestionarios_adaptados.html">Derechos sobre cuestionarios adaptados</a></li>
<li class="<?php
          if("/informacion-autores/politica.html"== $rutaplana or "/informacion-autores/politica.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-autores/politica.html">Política BiblioPRO</a></li>
<li class="<?php
          if("/informacion-autores/permiso.html"== $rutaplana or "/informacion-autores/permiso.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-autores/permiso.html">Dar permiso a BiblioPRO</a></li>

</ul>
</li>
<li class="<?php
          if("/informacion-autores/alternativas.html"== $rutaplana or "/informacion-autores/alternativas.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-autores/alternativas.html">Alternativas de reproducción y distribución</a></li>
<li class="<?php
          if("/informacion-autores/sesiones-informativas.html"== $rutaplana or "/informacion-autores/sesiones-informativas.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-autores/sesiones-informativas.html">Sesiones Informativas</a></li>
<li class="<?php
          if("/informacion-autores/contacto-autores.html"== $rutaplana or "/informacion-autores/contacto-autores.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-autores/contacto-autores.html">Contacto</a></li>

</ul>
