
<ul class="menu menu_vertical nav clearfix menu_normal">
<li class="<?php
          if("/informacion-patrocinio/porque-necesitamos.html"== $rutaplana or "/informacion-patrocinio/porque-necesitamos.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-patrocinio/porque-necesitamos.html">Porqué te necesitamos</a>
<ul>
<li class="<?php
          if("/informacion-patrocinio/porque-necesitamos.html"== $rutaplana or "/informacion-patrocinio/porque-necesitamos.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-patrocinio/porque-necesitamos.html">Porqué te necesitamos</a></li>
<li class="<?php
          if("/informacion-patrocinio/financiacion_del_proyecto.html"== $rutaplana or "/informacion-patrocinio/financiacion_del_proyecto.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-patrocinio/financiacion_del_proyecto.html">Financiación del proyecto</a></li>
<li class="<?php
          if("/informacion-patrocinio/actividades_presentes_y_futuras.html"== $rutaplana or "/informacion-patrocinio/actividades_presentes_y_futuras.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-patrocinio/actividades_presentes_y_futuras.html">Actividades presentes y futuras</a></li>

</ul>
</li>
<li class="<?php
          if("/informacion-patrocinio/patrocinadores/"== $rutaplana or "/informacion-patrocinio/patrocinadores/" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-patrocinio/patrocinadores/">Nuestros Patrocinadores</a></li>
<li class="<?php
          if("/informacion-patrocinio/donaciones.html"== $rutaplana or "/informacion-patrocinio/donaciones.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-patrocinio/donaciones.html">Donaciones</a></li>
<li class="<?php
          if("/informacion-patrocinio/contacto-patrocinadores.html"== $rutaplana or "/informacion-patrocinio/contacto-patrocinadores.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/informacion-patrocinio/contacto-patrocinadores.html">Contacto</a></li>

</ul>
