
<ul class="menu menu_vertical nav clearfix menu_normal">
<li class="<?php
          if("/que-es/index.html"== $rutaplana or "/que-es/index.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/que-es/index.html">Presentación</a></li>
<li class="<?php
          if("/que-es/porque.html"== $rutaplana or "/que-es/porque.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/que-es/porque.html">Por Qué</a></li>
<li class="<?php
          if("/que-es/objetivos.html"== $rutaplana or "/que-es/objetivos.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/que-es/objetivos.html">Objetivos</a></li>
<li class="<?php
          if("/que-es/contenidos.html"== $rutaplana or "/que-es/contenidos.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/que-es/contenidos.html">Contenidos</a></li>
<li class="<?php
          if("/que-es/comite-directivo"== $rutaplana or "/que-es/comite-directivo" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/que-es/comite-directivo">Colaboradores</a></li>
<li class="<?php
          if("/que-es/comite-cientifico"== $rutaplana or "/que-es/comite-cientifico" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/que-es/comite-cientifico">Comité Científico</a></li>

</ul>
