
<ul class="menu menu_vertical nav clearfix menu_normal">
<li class="<?php
          if("/mbp/index.html"== $rutaplana or "/mbp/index.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/mbp/index.html">Resumen</a></li>
<li class="<?php
          if("/mbp/datos.html"== $rutaplana or "/mbp/datos.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/mbp/datos.html">Mis datos</a></li>
<li class="<?php
          if("/mbp/descargas.html"== $rutaplana or "/mbp/descargas.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/mbp/descargas.html">Mis descargas</a></li>
<li class="<?php
          if("/mbp/sublicencias.html"== $rutaplana or "/mbp/sublicencias.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/mbp/sublicencias.html">Mis sublicencias</a></li>
<li class="<?php
          if("/mbp/donaciones.html"== $rutaplana or "/mbp/donaciones.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/mbp/donaciones.html">Mis donaciones</a></li>

</ul>
