
<ul class="menu menu_vertical nav clearfix menu_normal">
<li class="<?php
          if("/servicios/ivjornadabienvenida.html"== $rutaplana or "/servicios/ivjornadabienvenida.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/ivjornadabienvenida.html">IV Jornada Científica</a>
<ul>
<li class="<?php
          if("/servicios/ivjornadabienvenida.html"== $rutaplana or "/servicios/ivjornadabienvenida.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/ivjornadabienvenida.html">Bienvenida</a></li>
<li class="<?php
          if("/servicios/ivjornadaprograma.html"== $rutaplana or "/servicios/ivjornadaprograma.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/ivjornadaprograma.html">Programa científico</a></li>
<li class="<?php
          if("/servicios/iv_inscripcion.html"== $rutaplana or "/servicios/iv_inscripcion.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/iv_inscripcion.html">Inscripción</a></li>
<li class="<?php
          if("/servicios/resumenes_ivjornada.html"== $rutaplana or "/servicios/resumenes_ivjornada.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/resumenes_ivjornada.html">Envío de formularios </a></li>
<li class="<?php
          if("/servicios/streaming_ivjornada.html"== $rutaplana or "/servicios/streaming_ivjornada.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/streaming_ivjornada.html">Streaming Presentaciones</a></li>

</ul>
</li>
<li class="<?php
          if("/servicios/iiijornada-notadeprensa.html"== $rutaplana or "/servicios/iiijornada-notadeprensa.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/iiijornada-notadeprensa.html">III Jornada Científica</a>
<ul>
<li class="<?php
          if("/servicios/iiijornada-notadeprensa.html"== $rutaplana or "/servicios/iiijornada-notadeprensa.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/iiijornada-notadeprensa.html">Resumen de la Jornada</a></li>
<li class="<?php
          if("/servicios/iiijornadaprograma.html"== $rutaplana or "/servicios/iiijornadaprograma.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/iiijornadaprograma.html">Programa científico</a></li>
<li class="<?php
          if("/servicios/iiijornadapresentacion.html"== $rutaplana or "/servicios/iiijornadapresentacion.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/iiijornadapresentacion.html">Presentación</a></li>

</ul>
</li>
<li class="<?php
          if("/servicios/informacion_basica.html"== $rutaplana or "/servicios/informacion_basica.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/informacion_basica.html">Biblioteca</a>
<ul>
<li class="<?php
          if("/servicios/informacion_basica.html"== $rutaplana or "/servicios/informacion_basica.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/informacion_basica.html">Información Básica</a></li>
<li class="<?php
          if("/servicios/distribucion.html"== $rutaplana or "/servicios/distribucion.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/distribucion.html">Distribución de cuestionarios</a></li>
<li class="<?php
          if("/servicios/materiales.html"== $rutaplana or "/servicios/materiales.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/materiales.html">Materiales de ayuda</a></li>
<li class="<?php
          if("/servicios/como-funciona.html"== $rutaplana or "/servicios/como-funciona.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/como-funciona.html">Cómo funciona</a></li>

</ul>
</li>
<li class="<?php
          if("/servicios/entrada-datos.html"== $rutaplana or "/servicios/entrada-datos.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/entrada-datos.html">Servicio de entrada de datos</a></li>
<li class="<?php
          if("/servicios/formacion.html"== $rutaplana or "/servicios/formacion.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/formacion.html">Formación</a></li>
<li class="<?php
          if("/servicios/newsletter-y-noticias.html"== $rutaplana or "/servicios/newsletter-y-noticias.html" == $_SERVER["REQUEST_URI"]){
            ?>current<?php
            }
        ?>"><a href="/servicios/newsletter-y-noticias.html">Newsletter y Noticias</a></li>

</ul>
